POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "HealthCheck",
  "description": "Health check description",
  "date": "2023-11-03",
  "specialist": "Dr. Smith",
  "diagnosisCodes": ["D123", "D456"],
  "healthCheckRating": 1
}

